### ISSUE TITLE
Nullpointer exception in HBASEScan if input port does not have startRow, endRow or rowPrefix Attribute

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.hbase#106]
If the HBASEScan operator is used with an input port which has only the table name attribute a nullpointer exception is raised. 
That is the input the port does have none of the attributes startRow, endRow or rowPrefix.

The operator should emit a meaningful error message in such a case.

The exception:
at com.ibm.streamsx.hbase.HBASEScan.process(HBASEScan.java:901)
at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.processTuple(OperatorAdapter.java:1636)
at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:846)
at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:839)
at com.ibm.streams.operator.internal.ports.SwitchingHandler$Alternate.tuple(SwitchingHandler.java:162)

**Comment by anouri** [comment]
Corrected.
It is now possible to scan an HBASE table withe the following options:
1- only tableName as parameter or as input parameter tableNameAttribute.
2- tableName and startRow: In this case it delivers all rows from starRow till end of table.
3- tableName and endRow: In this case it delivers all rows from begin till endRow.
4- tableName, startRow and endRow. In this case it delivers all rows between startRow and endRow.

**Comment by anouri** [comment]
corrected in 
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.6.0
